name: Deploy via FTP

on:
  push:
    branches:
    - main
  schedule:
    - cron:  '0 8 * * *' # everyday at 8
  workflow_dispatch:

jobs:
  Build:
    runs-on: macos-latest
    steps:

    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.101.0'
        extended: true

    - name: Build site
      run: hugo --minify
      
    - name: Upload build files
      uses: actions/upload-artifact@v2
      with:
        path: public/

  Deploy:
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - name: Download build files
        uses: actions/download-artifact@v2

      - name: FTP site
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: alifelivedfully.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # remote_path: ''
          local_path: './artifact/*'
          
